# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Modelsim_Vivado/lab12_stopwatch/vivado/lab12_stopwatch.cache/wt [current_project]
set_property parent.project_path E:/Modelsim_Vivado/lab12_stopwatch/vivado/lab12_stopwatch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Modelsim_Vivado/lab12_stopwatch/vivado/lab12_stopwatch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_PulseWidth_conver.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_button_process_unit.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_contorler.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_debouncer.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_dffer.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_synchronizer.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/B_timer.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/D_display.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/P_bin2bcd.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/P_control.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/P_counter_n.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/T_counter.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/T_timing.v
  E:/Modelsim_Vivado/lab12_stopwatch/src/0_StopWatch.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Modelsim_Vivado/lab12_stopwatch/vivado/lab12_stopwatch.srcs/constrs_1/new/lab12_stopwatch.xdc
set_property used_in_implementation false [get_files E:/Modelsim_Vivado/lab12_stopwatch/vivado/lab12_stopwatch.srcs/constrs_1/new/lab12_stopwatch.xdc]


synth_design -top stopwatch -part xc7a35tcpg236-1


write_checkpoint -force -noxdef stopwatch.dcp

catch { report_utilization -file stopwatch_utilization_synth.rpt -pb stopwatch_utilization_synth.pb }
